<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('kpi_insights', function (Blueprint $table) {
            $table->id();
            $table->foreignId('measurement_id')->constrained()->cascadeOnDelete();
            $table->enum('quarter', ['Q1', 'Q2', 'Q3', 'Q4']);
            $table->unsignedSmallInteger('year');
            // Narative reasons generated by Gemini based on the final KPI
            // calculation done by Laravel. One row per KPI per period so it
            // can be auto-overwritten whenever fresh evidence comes in.
            $table->text('achieved_reason')->nullable();
            $table->text('not_achieved_reason')->nullable();
            $table->json('recommendations')->nullable();
            $table->json('raw_json')->nullable();
            $table->timestamps();

            // One insight per measurement per year/quarter: updateOrCreate
            // keeps this unique row refreshed on every new evidence.
            $table->unique(['measurement_id', 'year', 'quarter']);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('kpi_insights');
    }
};
